TOAST-DOCS/Compute-Image

- en/overview.md
- Reflect Korean content update
> Add English translation for 2021.11 release

- en/console-guide.md
- Translate updated content in Console Guide
- Translate the 'Copy to Another Region' section 
- Review and revise Console Guide
- Fix inaccurate, unnatural, or ungrammatical translation
- Improve parity with Korean content
- Fix typos
> English translation for 2022.01.25 release

- ko/public-api-gov.md
- ko/public-api.md
> Public API 조회시에 GPU 이미지 노출에 따른 변경점

- en/public-api.md
- Translate updated content
- Fix mistranslation and unnatural translation
- Fix grammar errors and typos
- Improve parity with Korean version
> Translate and review API guide for 2022.01.25 release

- en/public-api.md
> Elaborate translation

- ja/public-api.md
[#tc-iaas-compute/1198](https://nhnent.dooray.com/project/posts/3240020027640172035)
> [문서] 일본어 사용자 가이드 평촌 문구 수정

- zh/console-guide.md
- zh/overview.md
- zh/public-api.md
[#tc-iaas-compute/1171](https://nhnent.dooray.com/project/2399233537710930505/3224782194957178171?query=all%3D%25EC%2582%25AC%25EC%259A%25A9%25EC%259E%2590%2520%25EA%25B0%2580%25EC%259D%25B4%25EB%2593%259C)
Chinese -> English
> [문서] 중국어 사용자 가이드 현행화

- en/console-guide.md
- en/overview.md
- en/public-api.md
- Newly tranlsate the overview
- Fix inconsistency with the Korean version (missing tag in API guide)
- Improve parity wtih the Korean version (newline, whitespace)
> Review and revise the translation

- ko/public-api.md
[#(NHN-Cloud)Translation/4538](https://nhnent.dooray.com/project/posts/3300055253161715019) 댓글 참고
> 맴버 -> 멤버 오타 수정

- en/console-guide.md
Translate content added for the console guide
> Translation update for July release

- ko/public-api-gov.md
- ko/public-api.md
Dooray Info
- #tc-iaas-compute/1462
- [문서] Public API 로 이미지 업로드/다운로드 제공 설명 사용자 가이드에 추가
- https://nhnent.dooray.com/project/tasks/3478246359466103663
> [문서] public API 사용자 가이드 수정 - 이미지 업로드/다운로드

- en/console-guide.md
- en/overview.md
- en/public-api.md
> Translate update for Aug

- en/public-api.md
- ja/public-api.md
- ko/public-api.md
- zh/public-api.md
[tc-iaas-compute/1670](https://nhnent.dooray.com/project/posts/3625612817899616471)
> 이미지 사용자 가이드 공유 멤버 수 제한 삭제

- en/overview.md
> Translate update for Oct

- zh/overview.md
[tc-iaas-compute/1659](https://nhnent.dooray.com/project/posts/3620488473909656524)
#44 의 영문번역을 zh에 적용
> 공유 이미지에 대한 설명을 보다 명확하게 수정(중문)

- ko/public-api.md
https://nhnent.dooray.com/project/tasks/3620429346701034117
> 이미지 수정 API 추가

- en/public-api.md
> Translate update for Jan

- en/console-guide.md
> Translate update for Nov

- en/overview.md
- ja/overview.md
- ko/overview-gov.md
- ko/overview.md
- zh/overview.md
Dooray Info
* #tc-iaas-compute/2594
* [사용자가이드] 가이드 내 CentOS 내용 제거
* https://nhnent.dooray.com/project/tasks/4023413780552651029
> 가이드 내 CentOS 내용 제거

- ko/overview-ncgn.md
- ko/overview-ngoic.md
- ko/overview-ngovc.md
- ko/overview-ngsc.md
Dooray Info
* tc-iaas-compute/2876
* [Doc] NGOVC, NGOIC 문서 분리 작업
* https://nhnent.dooray.com/project/tasks/4114074563794294274
> NGOVC, NGOIC 문서 분리 작업

- ko/public-api-gov.md
- ko/public-api-ngsc.md
- ko/public-api.md
Dooray Info
* #tc-iaas-compute/2859
* [사용자가이드] 이미지 다운로드 가이드 개선
* https://nhnent.dooray.com/project/tasks/4103836916890786980
> 이미지 다운로드 가이드 개선

- ko/public-api-gov.md
- ko/public-api-ngsc.md
- ko/public-api.md
Dooray Info
* #tc-iaas-compute/2859
* [사용자가이드] 이미지 다운로드 가이드 개선
* https://nhnent.dooray.com/project/tasks/4103836916890786980
> 이미지 다운로드 가이드 개선2
